# Generated by Django 6.0 on 2026-03-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pushsubscription",
            name="auth",
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="endpoint",
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="p256dh",
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="fcm_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
